version: '3.9'

services:
  app:
    image: node:22-alpine
    container_name: piscioneri-tesi
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: sh -c "npm install && npx netlify dev"
    environment:
      - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}
      - VITE_OPENAI_ASSISTANT_ID=${VITE_OPENAI_ASSISTANT_ID}
      - VITE_APP_NAME=${VITE_APP_NAME}