#user node official image
services:
  app:
    image: node:22-alpine
    container_name: piscioneri-tesi
    ports:
      - 8888:8888
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx netlify dev"
    
